import { useState, useEffect } from "react";
import { PDFDownloadLink } from "@react-pdf/renderer";
import { motion } from "framer-motion";
import {
  FileSignature,
  Boxes,
  Network,
  History,
  ShieldCheck,
  Paperclip,
  FileDown,
  FileCode,
  Check,
  MoreHorizontal,
  Sparkles,
  ChevronDown,
  type LucideIcon,
} from "lucide-react";
import { colors, radius, shadow } from "@/ui/tokens/colors";
import { page } from "@/ui/tokens/layout";
import { H1, H3, Eyebrow, Body, BodySmall, Mono } from "@/ui/typography/Type";
import { Card } from "@/ui/primitives/Card";
import { Button } from "@/ui/primitives/Button";
import { Badge } from "@/ui/primitives/Badge";
import { IconTile } from "@/ui/primitives/IconTile";
import { ListRow } from "@/ui/primitives/ListRow";
import { useRouter } from "@/app/router";
import { useCases } from "@/lib/casesStore";
import { useEntities } from "@/lib/entitiesStore";
import { VellumPdfDocument } from "./PdfDocument";
import type { Case, Entity, Relation, Event as DomainEvent } from "@/lib/types";

// ── Section manifest ─────────────────────────────────────────────────────────
const SECTIONS: {
  idx: string;
  title: string;
  Icon: LucideIcon;
  tone: "ember" | "solar" | "moss" | "sky";
  active?: boolean;
}[] = [
  { idx: "01", title: "Cover · Case Summary",       Icon: FileSignature, tone: "ember", active: true },
  { idx: "02", title: "Entities Index",             Icon: Boxes,         tone: "sky" },
  { idx: "03", title: "Relations Map",              Icon: Network,       tone: "moss" },
  { idx: "04", title: "Timeline · Ledger",          Icon: History,       tone: "solar" },
  { idx: "05", title: "Hash Chain Verification",    Icon: ShieldCheck,   tone: "ember" },
  { idx: "06", title: "Appendix · Attachments",     Icon: Paperclip,     tone: "sky" },
];

// ── Markdown exporter ────────────────────────────────────────────────────────
function summarizeEventMd(e: DomainEvent): string {
  const p = e.payload as Record<string, unknown>;
  switch (e.kind) {
    case "case.create":     return `Case opened — ${p.title ?? ""}`;
    case "case.status":     return `Status changed ${p.from} → ${p.to}`;
    case "entity.create":   return `Added ${p.kind ?? "entity"} · ${p.label ?? p.id ?? ""}`;
    case "relation.create": return `Linked ${p.from} → ${p.to} (${p.kind})`;
    case "enrich.hibp":     return `HIBP: ${(p.breaches as string[] | undefined)?.length ?? 0} breaches`;
    case "enrich.whois":    return `Whois: ${p.domain} registered ${p.registered}`;
    case "note":            return `Note — ${String(p.body ?? "").slice(0, 80)}`;
    default:                return e.kind;
  }
}

function downloadMarkdown(
  c: Case,
  entities: Entity[],
  relations: Relation[],
  events: DomainEvent[],
) {
  const entityMap = new Map(entities.map((e) => [e.id, e]));
  const lines = [
    `# ${c.title}`,
    ``,
    `**Type:** ${c.kind}  `,
    `**Status:** ${c.status}  `,
    `**Opened:** ${new Date(c.createdAt).toLocaleDateString("en-GB")}  `,
    `**Case ID:** \`${c.id.toUpperCase()}\`  `,
    ``,
    `---`,
    ``,
    `## Entities (${entities.length})`,
    ``,
    `| Kind | Label | Confidence | First seen |`,
    `|------|-------|------------|------------|`,
    ...entities.map(
      (e) =>
        `| ${e.kind} | ${e.label} | ${Math.round(e.confidence * 100)}% | ${new Date(e.firstSeen).toLocaleDateString("en-GB")} |`
    ),
    ``,
    `## Relations (${relations.length})`,
    ``,
    `| From | Kind | To | Confidence |`,
    `|------|------|----|------------|`,
    ...relations.map((r) => {
      const from = entityMap.get(r.fromEntity)?.label ?? r.fromEntity.slice(0, 8);
      const to = entityMap.get(r.toEntity)?.label ?? r.toEntity.slice(0, 8);
      return `| ${from} | ${r.kind} | ${to} | ${Math.round(r.confidence * 100)}% |`;
    }),
    ``,
    `## Timeline (${events.length} events)`,
    ``,
    ...events.map(
      (e) =>
        `- **[${e.ts.slice(0, 19).replace("T", " ")}]** \`${e.kind}\` — ${summarizeEventMd(e)}`
    ),
    ``,
    `---`,
    `*Generated by Vellum OSINT Studio · ${new Date().toLocaleDateString("en-GB")}*`,
  ];

  const blob = new Blob([lines.join("\n")], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `vellum-${c.title.toLowerCase().replace(/\s+/g, "-")}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ── Component ────────────────────────────────────────────────────────────────
export function ReportsScreen() {
  const routerCaseId = useRouter((s) => s.caseId);
  const cases = useCases((s) => s.cases.filter((c) => c.status !== "Archived"));
  const load = useEntities((s) => s.load);
  const byCase = useEntities((s) => s.byCase);

  // Selected case: prefer router's caseId, fall back to first case
  const [selectedCaseId, setSelectedCaseId] = useState<string | null>(
    routerCaseId ?? (cases.length > 0 ? cases[0].id : null)
  );
  const [pickerOpen, setPickerOpen] = useState(false);

  // Sync with router when it changes
  useEffect(() => {
    if (routerCaseId) setSelectedCaseId(routerCaseId);
  }, [routerCaseId]);

  // Default to first case when cases load
  useEffect(() => {
    if (!selectedCaseId && cases.length > 0) {
      setSelectedCaseId(cases[0].id);
    }
  }, [cases, selectedCaseId]);

  // Load data
  useEffect(() => {
    if (selectedCaseId && !byCase[selectedCaseId]) {
      load(selectedCaseId);
    }
  }, [selectedCaseId, load, byCase]);

  const c = cases.find((x) => x.id === selectedCaseId) ?? null;
  const caseData = selectedCaseId ? byCase[selectedCaseId] : null;
  const entities = caseData?.entities ?? [];
  const relations = caseData?.relations ?? [];
  const events = caseData?.events ?? [];
  const dataLoading = caseData?.loading ?? false;

  const compiledAt = new Date().toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });

  return (
    <div style={{ ...page.standard }}>
      <div style={{ marginBottom: 28 }}>
        <Eyebrow>Composer · chain-of-custody report</Eyebrow>
        <H1 style={{ marginTop: 6 }}>Report</H1>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1.15fr", gap: 28 }}>
        {/* ── Editor side ──────────────────────────────────────────────── */}
        <div style={{ display: "flex", flexDirection: "column", gap: 18 }}>

          {/* Case picker */}
          <Card padding="16px 20px">
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }}>
              <Eyebrow>Subject case</Eyebrow>
            </div>
            <div style={{ position: "relative" }}>
              <button
                onClick={() => setPickerOpen((v) => !v)}
                style={{
                  width: "100%",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                  padding: "10px 14px",
                  background: colors.paperWarm,
                  border: `1px solid ${colors.hairlineStrong}`,
                  borderRadius: radius.md,
                  cursor: "pointer",
                  gap: 8,
                }}
              >
                <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                  {c ? (
                    <>
                      <div
                        style={{
                          width: 8,
                          height: 8,
                          borderRadius: 999,
                          background:
                            c.accent === "ember" ? colors.ember :
                            c.accent === "solar" ? "#A07810" :
                            c.accent === "moss"  ? colors.moss : colors.ink,
                          flexShrink: 0,
                        }}
                      />
                      <Mono style={{ fontSize: 12, color: colors.ink }}>{c.title}</Mono>
                    </>
                  ) : (
                    <Mono style={{ fontSize: 12, color: colors.inkMute }}>Select a case…</Mono>
                  )}
                </div>
                <ChevronDown
                  size={13}
                  strokeWidth={1.8}
                  color={colors.inkMute}
                  style={{ transform: pickerOpen ? "rotate(180deg)" : "none", transition: "transform 150ms" }}
                />
              </button>

              {pickerOpen && cases.length > 0 && (
                <div
                  style={{
                    position: "absolute",
                    top: "calc(100% + 6px)",
                    left: 0,
                    right: 0,
                    background: colors.paper,
                    border: `1px solid ${colors.hairlineStrong}`,
                    borderRadius: radius.md,
                    boxShadow: shadow.md,
                    zIndex: 40,
                    overflow: "hidden",
                  }}
                >
                  {cases.map((ca) => (
                    <button
                      key={ca.id}
                      onClick={() => { setSelectedCaseId(ca.id); setPickerOpen(false); }}
                      style={{
                        width: "100%",
                        display: "flex",
                        alignItems: "center",
                        gap: 10,
                        padding: "10px 14px",
                        background: ca.id === selectedCaseId ? colors.paperWarm : "transparent",
                        cursor: "pointer",
                        borderBottom: `1px solid ${colors.hairline}`,
                        textAlign: "left",
                      }}
                    >
                      <div
                        style={{
                          width: 7,
                          height: 7,
                          borderRadius: 999,
                          flexShrink: 0,
                          background:
                            ca.accent === "ember" ? colors.ember :
                            ca.accent === "solar" ? "#A07810" :
                            ca.accent === "moss"  ? colors.moss : colors.ink,
                        }}
                      />
                      <Mono style={{ fontSize: 11, color: colors.ink }}>{ca.title}</Mono>
                      <div style={{ marginLeft: "auto" }}>
                        <Badge tone={ca.kind === "Cyber" ? "ember" : ca.kind === "Person" ? "sky" : ca.kind === "Brand" ? "solar" : "paper"}>
                          {ca.kind}
                        </Badge>
                      </div>
                    </button>
                  ))}
                </div>
              )}
            </div>

            {c && !dataLoading && (
              <div style={{ display: "flex", gap: 8, marginTop: 12 }}>
                <Mono style={{ fontSize: 11, color: colors.inkFade }}>{entities.length} entities</Mono>
                <Mono style={{ fontSize: 11, color: colors.hairlineStrong }}>·</Mono>
                <Mono style={{ fontSize: 11, color: colors.inkFade }}>{relations.length} relations</Mono>
                <Mono style={{ fontSize: 11, color: colors.hairlineStrong }}>·</Mono>
                <Mono style={{ fontSize: 11, color: colors.inkFade }}>{events.length} events</Mono>
              </div>
            )}
            {dataLoading && (
              <Mono style={{ fontSize: 11, color: colors.inkFade, marginTop: 8 }}>Loading…</Mono>
            )}
          </Card>

          {/* Sections */}
          <Card padding="22px 24px">
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }}>
              <H3>Sections</H3>
              <Mono style={{ color: colors.inkFade }}>06</Mono>
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
              {SECTIONS.map((s) => (
                <ListRow
                  key={s.idx}
                  emphasis={s.active}
                  leading={
                    <IconTile tone={s.tone} size={36} filled={s.active}>
                      <s.Icon size={16} strokeWidth={1.8} />
                    </IconTile>
                  }
                  title={s.title}
                  subtitle={`Section ${s.idx}`}
                  trailing={<MoreHorizontal size={16} strokeWidth={1.8} color={colors.inkFade} />}
                />
              ))}
            </div>
          </Card>

          {/* Export */}
          <Card tone="ink" padding="22px 24px">
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }}>
              <Eyebrow color={colors.solar}>Export</Eyebrow>
              <Badge tone="moss" dot>Chain verified</Badge>
            </div>
            <Body style={{ color: "rgba(245,239,224,0.85)" }}>
              PDF includes a verification page with the HMAC chain. Re-run via{" "}
              <span style={{ fontFamily: "var(--font-mono)", color: colors.solar }}>
                vellum verify report.pdf
              </span>{" "}
              to confirm integrity.
            </Body>
            <div style={{ display: "flex", gap: 10, marginTop: 16 }}>
              {c ? (
                <PDFDownloadLink
                  document={
                    <VellumPdfDocument
                      c={c}
                      entities={entities}
                      relations={relations}
                      events={events}
                    />
                  }
                  fileName={`vellum-${c.title.toLowerCase().replace(/\s+/g, "-")}.pdf`}
                  style={{ textDecoration: "none" }}
                >
                  {({ loading: pdfLoading }) => (
                    <Button
                      variant="ember"
                      size="md"
                      icon={<FileDown size={16} strokeWidth={1.8} />}
                      disabled={pdfLoading || dataLoading}
                    >
                      {pdfLoading ? "Building…" : "Generate PDF"}
                    </Button>
                  )}
                </PDFDownloadLink>
              ) : (
                <Button variant="ember" size="md" icon={<FileDown size={16} strokeWidth={1.8} />} disabled>
                  Generate PDF
                </Button>
              )}
              <Button
                variant="ghost"
                size="md"
                icon={<FileCode size={16} strokeWidth={1.8} />}
                disabled={!c || dataLoading}
                onClick={() => c && downloadMarkdown(c, entities, relations, events)}
                style={{
                  background: "rgba(245,239,224,0.08)",
                  color: colors.paper,
                  opacity: !c ? 0.45 : 1,
                }}
              >
                Markdown
              </Button>
            </div>
          </Card>
        </div>

        {/* ── A4 preview ───────────────────────────────────────────────── */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.45, ease: [0.32, 0.72, 0, 1] }}
        >
          <div
            style={{
              aspectRatio: "1 / 1.414",
              background: colors.paperLow,
              borderRadius: radius.xl,
              boxShadow: shadow.lg,
              padding: "44px 48px",
              position: "relative",
              overflow: "hidden",
              border: `1px solid ${colors.hairline}`,
            }}
          >
            {/* Page header */}
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                paddingBottom: 16,
                borderBottom: `1px solid ${colors.hairline}`,
              }}
            >
              <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                <div
                  style={{
                    width: 28,
                    height: 28,
                    background: colors.ink,
                    color: colors.paper,
                    borderRadius: radius.sm,
                    display: "grid",
                    placeItems: "center",
                    fontFamily: "var(--font-display)",
                    fontWeight: 800,
                    fontSize: 13,
                  }}
                >
                  V
                </div>
                <Eyebrow>Vellum · {c ? c.title : "no case selected"}</Eyebrow>
              </div>
              <Mono style={{ color: colors.inkFade }}>page 01</Mono>
            </div>

            {/* Title */}
            <div style={{ marginTop: 32 }}>
              <Badge tone="ember" dot>Confidential</Badge>
              <H1 style={{ marginTop: 12 }}>
                {c ? c.title : <span style={{ color: colors.inkMute }}>Select a case</span>}
              </H1>
              <BodySmall style={{ marginTop: 8, color: colors.inkMute }}>
                {c
                  ? `Compiled ${compiledAt} · ${entities.length} entities · ${relations.length} relations · ${events.length} events`
                  : "No case loaded — pick one from the panel on the left."
                }
              </BodySmall>
            </div>

            {/* Stat chips */}
            <div style={{ marginTop: 28, display: "flex", gap: 10, flexWrap: "wrap" }}>
              <Chip tone="ember" Icon={Boxes}       label={String(entities.length)}  sub="entities" />
              <Chip tone="moss"  Icon={Sparkles}    label={String(relations.length)} sub="relations" />
              <Chip tone="solar" Icon={History}     label={String(events.length)}    sub="events" />
              <Chip tone="sky"   Icon={ShieldCheck} label="OK"                       sub="chain ok" />
            </div>

            {/* Case meta */}
            {c && (
              <div style={{ marginTop: 24 }}>
                <Eyebrow>§01 · Case information</Eyebrow>
                {[
                  ["Type",    c.kind],
                  ["Status",  c.status],
                  ...(c.legalBasis ? [["Legal basis", c.legalBasis]] : []),
                  ["Opened",  new Date(c.createdAt).toLocaleDateString("en-GB")],
                ].map(([k, v]) => (
                  <div
                    key={k}
                    style={{
                      display: "flex",
                      gap: 12,
                      padding: "6px 0",
                      borderBottom: `1px solid ${colors.hairline}`,
                    }}
                  >
                    <Mono style={{ width: 100, fontSize: 10.5, color: colors.inkMute, flexShrink: 0 }}>{k}</Mono>
                    <Mono style={{ fontSize: 10.5, color: colors.ink }}>{v}</Mono>
                  </div>
                ))}
              </div>
            )}

            {/* Footer chip */}
            <div
              style={{
                position: "absolute",
                left: 48,
                bottom: 28,
                display: "flex",
                gap: 8,
              }}
            >
              <Badge tone="paper">
                {c ? `ID ${c.id.slice(0, 6).toUpperCase()}` : "No case"}
              </Badge>
              <Badge tone="ember">Confidential</Badge>
            </div>

            {/* HMAC stamp */}
            <div
              style={{
                position: "absolute",
                right: 36,
                bottom: 28,
                display: "flex",
                alignItems: "center",
                gap: 10,
                padding: "8px 14px 8px 8px",
                background: colors.emberSoft,
                borderRadius: radius.pill,
                border: `1px solid ${colors.ember}`,
              }}
            >
              <IconTile tone="ember" size={26} filled>
                <Check size={12} strokeWidth={2.5} />
              </IconTile>
              <Mono style={{ color: colors.ember, fontSize: 11 }}>
                HMAC · {events.length > 0 ? events[events.length - 1].hash.slice(0, 8) + "…" : "0x——"}
              </Mono>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
}

// ── Chip subcomponent ────────────────────────────────────────────────────────
function Chip({
  tone,
  Icon,
  label,
  sub,
}: {
  tone: "ember" | "solar" | "moss" | "sky";
  Icon: LucideIcon;
  label: string;
  sub: string;
}) {
  const bg =
    tone === "ember" ? colors.emberSoft :
    tone === "solar" ? colors.solarSoft :
    tone === "moss"  ? colors.mossSoft  :
                       colors.skySoft;
  const fg =
    tone === "ember" ? colors.ember :
    tone === "solar" ? "#A07810" :
    tone === "moss"  ? colors.moss :
                       colors.sky;
  return (
    <div
      style={{
        background: bg,
        color: fg,
        padding: "12px 14px",
        borderRadius: radius.lg,
        display: "flex",
        flexDirection: "column",
        gap: 4,
        minWidth: 84,
      }}
    >
      <Icon size={14} strokeWidth={2} style={{ opacity: 0.85 }} />
      <span style={{ fontFamily: "var(--font-display)", fontWeight: 800, fontSize: 20, letterSpacing: "-0.02em", marginTop: 2 }}>
        {label}
      </span>
      <span style={{ fontSize: 11, fontWeight: 500, opacity: 0.75 }}>{sub}</span>
    </div>
  );
}
